apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media_big-green"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "200Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/big-green/plex"